### ISSUE TITLE
关于线程问题

### ISSUE THREAD

**Issue by chenbt-hz** [ZW-xjtlu/exomePeak2#2]
你好：

  近期我在使用exomePeak包进行peakcalling，由于数据量较大（2个样本，3个生物学重复，每个约20G数据），计算十分缓慢（约1小时计算1%），我使用的服务器性能充足却无法发挥，而我也没有在手册中找到有关**多线程**的参数。

请问exomePeak2是否有助于加快运算速度，或者能提供线程控制参数呢？如果仍使用exomePeak包有无其他办法提高速度呢？

  谢谢指导！

**Comment by DrWangL** [comment]
I found there's a parameter "parallel" which is set to  "FALSE" by default.Maybe you can try to set it to TRUE and run again.
But then again,I never tried this.
Hope it helps.

**Comment by MethTo** [comment]
Thanks for your reply, I will try it.

**Comment by MethTo** [comment]
Thanks for your reply, I will try it.
