### ISSUE TITLE
使用exomePeak2进行peak calling时，程序被kill掉

### ISSUE THREAD

**Issue by 1JYL123** [ZW-xjtlu/exomePeak2#26]
作者您好，我最近在服务器上使用exomePeak2时，程序总是被kill，请问一下解决方法。
IFN <- exomePeak2(bam_ip=IP_IFN_BAM, bam_input=Input_IFN_BAM, parallel=1, gff="/data1/gaoronghui/Homo_sapiens/Homo_sapiens.GRCh38.104.chr_patch_hapl_scaff.gtf", genome= "BSgenome.Hsapiens.NCBI.GRCh38")
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Extract bin features ... OK
Count reads on bin features ... Killed

**Comment by Ganz20** [comment]
exomePeak2 need a big memory.  You need another machine with a bigger physical memory to run your analysis.
