### ISSUE TITLE
Calculate bin GC contents on exons ... Error in h(simpleError(msg, call)) 

### ISSUE THREAD

**Issue by Ganz20** [ZW-xjtlu/exomePeak2#35]
Hello, 
Try to use exomePeak2 for peak calling, yet it output error.
bam files were aligned to ensembl mus musculus GRCm38 GTF which is the same assigned by 'gtfpath'. 
genome were aligned as mm10.
It ran for a while then stopped with an error as shown below.
How can I fix it?
Thanks,

-------------------------------------------------------------------------------------------------------------------------------------------------------
> exomePeak2(bam_ip = IP_BAM, bam_input = INPUT_BAM, gff = gtfpath, genome = "mm10", save_dir=savepath)
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Extract bin features ... OK
Count reads on bin features ... OK
Identify background features ... OK
Estimate sample sepecific size factors from the background ... OK
Calculate bin GC contents on exons ... Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'letterFrequency': error in evaluating the argument 'x' in selecting a method for function 'XStringSet': The following seqlevels are to be dropped but are currently in use
  (i.e. have ranges on them): 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, X, Y, MT, GL456210.1, GL456211.1, GL456212.1,
  GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1,
  GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1,
  JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1,
  JH584303.1, JH584304.1. Please use the 'pruning.mode' argument to
  control how to prune 'x', that is, how to remove the ranges in 'x' that
  are on these sequences. For example, do something like:
    seqlevels(x, pruning.mode="coarse") <- new_seqlevels
  or:
    keepSeqlevels(x, new_seqlevels, pruning.mode="coarse")
  See ?seqinfo for a description of the pruning modes.
In addition: Warning messages:
1: In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
2: In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by ZW-xjtlu** [comment]
Dear exomePeak2 user，

I recommend to use genome reference and gene annotation from UCSC to performe exomePeak2 analysis with GC content bias correction. Alternatively，you could try to leave the genome argument and run the analysis without correcting GC bias.

Best wishes，
Zhen

**Comment by Ganz20** [comment]
Thank you for the timely reply. 
I tried adding an option plot_gc=FALSE in the command, yet got the same error.  
To solve this issue,  I aligned sequences to ucsc mm39 (downloaded from https://hgdownload.soe.ucsc.edu/goldenPath/mm39/bigZips/) and ran the command as below:
exomePeak2(bam_ip=CON_IP_BAM, bam_input=CON_INPUT_BAM, bam_input_treated=TRE_INPUT_BAM, bam_ip_treated=TRE_IP_BAM, gff=gtfpath, genome="mm39")
gff was the mm39.refGene.gtf.
The command ran and generated ouputs,  along with many warns, something like below:
 -----------------------------
_There were 50 or more warnings (use warnings() to see the first 50)
......
50: In .merge_two_Seqinfo_objects(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': UNMAPPED
  - in 'y': chr1_GL456210v1_random, chr1_GL456239v1_random, chr4_JH584295v1_random, chrM, chrUn_GL456359v1, chrUn_GL456360v1, chrUn_GL456366v1, chrUn_GL456367v1, chrUn_GL456368v1, chrUn_GL456370v1, chrUn_GL456372v1, chrUn_GL456378v1, chrUn_GL456379v1, chrUn_GL456381v1, chrUn_GL456382v1, chrUn_GL456383v1, chrUn_GL456385v1, chrUn_GL456387v1, chrUn_GL456389v1, chrUn_GL456390v1, chrUn_GL456392v1, chrUn_GL456394v1, chrUn_GL456396v1, chrUn_MU069435v1, chrY_JH584301v1_random, chrY_JH584302v1_random, chrY_JH584303v1_random
  Make sure to always combine/compare objects based on the same reference_

Here are two questions:
**1. which gtf was assigned with the option genome="mm39"? Is it the refGene or something else like knownGene?
2. What did these warns mean, did it have an impact on the results?**

To strictly use the same genome and annotation, I generated a splite file using the refGene.gtf by makeTxDbFromGFF (a function from Bioconductor GenomicFeatures package), and used this splite as below:
exomePeak2(bam_ip=CON_IP_BAM, bam_input=CON_INPUT_BAM, bam_input_treated=TRE_INPUT_BAM, bam_ip_treated=TRE_IP_BAM, gff=gtfpath, txdb =mm39_txdb)

The command ran smoothly, generated result with one warning:
_Warning message:
In diffAnalysis(bam_IP = bam_ip, bam_input = bam_input, bam_IP_treated = bam_ip_treated,  :
  Reference genome not provided, GC content bias is left uncorrected._

It seemed that the txdb option didn't work? What's the impact of this issue? 

Thanks,

**Comment by Ganz20** [comment]
After tested exomePeak2 many times,  here are some answers. 
1. Though it is said "genome" is not a required option,  it is better to set up 'genome', otherwise, you will get a warning as genome not assigned. 
 2. You have to use UCSC reference genome for the alignment. Alignment to an Ensembl reference, even if you make your txdb using the exact GTF/GFF, you will still have kinds of errors or warning. The output would be doubtable.
