### ISSUE TITLE
weird result with test_method=DESeq2

### ISSUE THREAD

**Issue by Ganz20** [ZW-xjtlu/exomePeak2#39]
Hi, I am trying to use DESeq2 as the test method. The command ran, but it generated 2 records only while the default test method generated >6000 records. 
I attached the command and output log below. What could be the potential cause and how can I fix it?

> > exomePeak2(bam_ip=CON_IP_BAM, bam_input=CON_INPUT_BAM, bam_input_treated=TRE_INPUT_BAM, bam_ip_treated=TRE_IP_BAM, gff=gtfpath, txdb=txdb, test_method="DESeq2", p_cutoff=0.05, save_dir=outputpath)
> Extract bin features ... OK
> Count reads on bin features ... OK
> Identify background features ... OK
> Estimate sample sepecific size factors from the background ... OK
> Detect peaks with GLM ... gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> OK
> Count reads on peaks ... OK
> Calculate offset matrix for peaks ... OK
> Detect differentially modified peaks with interactive GLM ... gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> OK
> GRangesList object of length 2:
> $`1`
> GRanges object with 2 ranges and 0 metadata columns:
>     seqnames            ranges strand
>        <Rle>         <IRanges>  <Rle>
>   1        3 95031787-95031912      +
>   1        3 95032508-95032531      +
>   seqinfo: 61 sequences from an unspecified genome; no seqlengths
> $`2`
> GRanges object with 1 range and 0 metadata columns:
>     seqnames          ranges strand
>        <Rle>       <IRanges>  <Rle>
>   2       19 5473563-5473712      -
>   -------
>   seqinfo: 61 sequences from an unspecified genome; no seqlengths
> Warning message:
> In diffAnalysis(bam_IP = bam_ip, bam_input = bam_input, bam_IP_treated = bam_ip_treated,  :
>   Reference genome not provided, GC content bias is left uncorrected.

**Comment by ZW-xjtlu** [comment]
Dear exomePeak2 User,

I recommend using a more lenient (higher) p-value filter when setting the test method to "DESeq2". For instance, you might choose p_cutoff = 0.01 in the main function. DESeq2's method, which accounts for over-dispersion parameters, is notably more stringent. Adjusting the p-value threshold in this manner is crucial to achieving sensitive outputs that are on par with those from the Poisson mode.

Best regards,
Zhen Wei
